global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ryssroad#7010
    light-cache-size: 20
chains:
    gaia:
        type: cosmos
        value:
            key: gaiakey
            chain-id: GAIA
            rpc-addr: https://gaia-fleet.poolparty.stridenet.co:443
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.000uatom
            debug: true
            timeout: 20s
            output-format: json
            sign-mode: direct
    osmo:
        type: cosmos
        value:
            key: osmokey
            chain-id: osmo-test-4
            rpc-addr: https://rpc-test.osmosis.zone:443
            account-prefix: osmo
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.001uosmo
            debug: true
            timeout: 20s
            output-format: json
            sign-mode: direct
    stride:
        type: cosmos
        value:
            key: stridekey
            chain-id: STRIDE-TESTNET-4
            rpc-addr: http://127.0.0.1:16657
            account-prefix: stride
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.001ustrd
            debug: true
            timeout: 20s
            output-format: json
            sign-mode: direct
paths:
    icq:
        src:
            chain-id: STRIDE-TESTNET-4
            client-id: 07-tendermint-0
            connection-id: connection-0
        dst:
            chain-id: GAIA
            client-id: 07-tendermint-0
            connection-id: connection-0
        src-channel-filter:
            rule: allowlist
            channel-list:
                - channel-5
                - channel-10
                - channel-11
                - channel-12
                - channel-13
                - channel-14
    strgaia:
        src:
            chain-id: STRIDE-TESTNET-4
            client-id: 07-tendermint-0
            connection-id: connection-0
        dst:
            chain-id: GAIA
            client-id: 07-tendermint-0
            connection-id: connection-0
        src-channel-filter:
            rule: allowlist
            channel-list:
                - channel-0
                - channel-1
                - channel-2
                - channel-3
                - channel-4
